"""Generators: NIMServiceGenerator, OpenAPIGenerator, DockerfileGenerator.

Each generator takes a ModelMetadata object and produces files in an output directory.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Dict, List, Optional

from .inspector import ModelMetadata, TensorInfo


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dtype_to_python(dtype: str) -> str:
    mapping = {
        "float32": "float",
        "float64": "float",
        "float16": "float",
        "bfloat16": "float",
        "int8":  "int",
        "int16": "int",
        "int32": "int",
        "int64": "int",
        "uint8":  "int",
        "uint16": "int",
        "uint32": "int",
        "uint64": "int",
        "bool":   "bool",
        "string": "str",
    }
    return mapping.get(dtype, "float")


def _dtype_to_openapi(dtype: str) -> Dict:
    if "float" in dtype:
        return {"type": "number", "format": "float"}
    if "int" in dtype or dtype == "bool":
        return {"type": "integer"}
    return {"type": "string"}


def _tensor_to_pydantic_field(t: TensorInfo) -> str:
    """Return the Pydantic field declaration for one tensor."""
    py_type = _dtype_to_python(t.dtype)
    shape_comment = t.shape_str()
    # Flatten to a nested List type hint reflecting the ndim
    ndim = len(t.shape) if t.shape else 1
    type_hint = py_type
    for _ in range(ndim):
        type_hint = f"List[{type_hint}]"
    return f'    {t.name}: {type_hint}  # shape {shape_comment}, dtype {t.dtype}'


# ---------------------------------------------------------------------------
# NIMServiceGenerator
# ---------------------------------------------------------------------------

class NIMServiceGenerator:
    """Generate a FastAPI application stub from model metadata."""

    def __init__(self, metadata: ModelMetadata):
        self.meta = metadata

    def generate(self, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        app_path = output_dir / "app.py"
        app_path.write_text(self._render(), encoding="utf-8")
        return app_path

    def _render(self) -> str:
        name = self.meta.name
        inputs_fields = "\n".join(_tensor_to_pydantic_field(t) for t in self.meta.inputs)
        outputs_fields = "\n".join(_tensor_to_pydantic_field(t) for t in self.meta.outputs)

        input_names = [t.name for t in self.meta.inputs]
        output_names = [t.name for t in self.meta.outputs]

        predict_kwargs = ", ".join(f"{n}=req.{n}" for n in input_names)
        mock_outputs = "\n        ".join(
            f"{n}=[],"  for n in output_names
        )

        return textwrap.dedent(f'''\
            """
            NIM-style microservice for model: {name}
            Generated by nimify-anything.

            Opset: {self.meta.opset_version}
            IR version: {self.meta.ir_version}
            """
            from __future__ import annotations

            import time
            from typing import List

            from fastapi import FastAPI, HTTPException
            from fastapi.responses import PlainTextResponse
            from pydantic import BaseModel
            from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

            # ---------------------------------------------------------------------------
            # Request / Response models
            # ---------------------------------------------------------------------------

            class PredictRequest(BaseModel):
                """Inputs derived from ONNX graph inputs."""
            {inputs_fields}


            class PredictResponse(BaseModel):
                """Outputs derived from ONNX graph outputs."""
            {outputs_fields}


            # ---------------------------------------------------------------------------
            # Prometheus metrics
            # ---------------------------------------------------------------------------

            REQUEST_COUNTER = Counter(
                "nim_requests_total", "Total prediction requests", ["status"]
            )
            REQUEST_LATENCY = Histogram(
                "nim_request_latency_seconds", "Prediction latency", buckets=[.005, .01, .025, .05, .1, .25, .5, 1, 2.5]
            )

            # ---------------------------------------------------------------------------
            # App
            # ---------------------------------------------------------------------------

            app = FastAPI(
                title="{name} NIM API",
                version="0.2.0",
                description="NVIDIA NIM-style inference microservice",
            )

            _start_time = time.time()


            @app.post("/predict", response_model=PredictResponse, summary="Run model inference")
            async def predict(req: PredictRequest) -> PredictResponse:
                """
                Execute prediction.

                Replace the stub below with real ONNX Runtime inference:

                    import onnxruntime as ort, numpy as np
                    session = ort.InferenceSession("model.onnx", providers=["CUDAExecutionProvider"])
                    result = session.run(None, {{k: np.array(v) for k, v in req.dict().items()}})
                """
                start = time.time()
                try:
                    # --- STUB: replace with real inference ---
                    response = PredictResponse(
                        {mock_outputs}
                    )
                    REQUEST_COUNTER.labels(status="success").inc()
                    return response
                except Exception as exc:
                    REQUEST_COUNTER.labels(status="error").inc()
                    raise HTTPException(status_code=500, detail=str(exc)) from exc
                finally:
                    REQUEST_LATENCY.observe(time.time() - start)


            @app.get("/health", summary="Health check")
            async def health():
                return {{
                    "status": "healthy",
                    "model": "{name}",
                    "uptime_seconds": round(time.time() - _start_time, 1),
                }}


            @app.get("/ready", summary="Readiness probe")
            async def ready():
                # Add model-load check here if needed
                return {{"status": "ready"}}


            @app.get("/metrics", response_class=PlainTextResponse, summary="Prometheus metrics")
            async def metrics():
                return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)


            if __name__ == "__main__":
                import uvicorn
                uvicorn.run(app, host="0.0.0.0", port=8000)
        ''')


# ---------------------------------------------------------------------------
# OpenAPIGenerator
# ---------------------------------------------------------------------------

class OpenAPIGenerator:
    """Generate an OpenAPI 3.0 spec JSON from model I/O signatures."""

    def __init__(self, metadata: ModelMetadata):
        self.meta = metadata

    def generate(self, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        spec_path = output_dir / "openapi.json"
        spec_path.write_text(json.dumps(self._build(), indent=2), encoding="utf-8")
        return spec_path

    def _tensor_schema(self, t: TensorInfo) -> Dict:
        ndim = len(t.shape) if t.shape else 1
        inner = _dtype_to_openapi(t.dtype)
        schema: Dict = inner
        for i in range(ndim):
            dim = t.shape[-(i + 1)] if t.shape else None
            item_schema = schema
            schema = {"type": "array", "items": item_schema}
            if dim is not None:
                schema["minItems"] = dim
                schema["maxItems"] = dim
        schema["description"] = f"dtype={t.dtype}, shape={t.shape_str()}"
        return schema

    def _body_schema(self, tensors: List[TensorInfo]) -> Dict:
        return {
            "type": "object",
            "required": [t.name for t in tensors],
            "properties": {t.name: self._tensor_schema(t) for t in tensors},
        }

    def _build(self) -> Dict:
        name = self.meta.name
        return {
            "openapi": "3.0.0",
            "info": {
                "title": f"{name} NIM API",
                "version": "0.2.0",
                "description": (
                    f"NVIDIA NIM-style inference microservice for `{name}`. "
                    f"ONNX opset {self.meta.opset_version}."
                ),
            },
            "servers": [{"url": "http://localhost:8000", "description": "Local dev"}],
            "paths": {
                "/predict": {
                    "post": {
                        "summary": "Run model inference",
                        "operationId": "predict",
                        "tags": ["inference"],
                        "requestBody": {
                            "required": True,
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/PredictRequest"
                                    }
                                }
                            },
                        },
                        "responses": {
                            "200": {
                                "description": "Prediction result",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "$ref": "#/components/schemas/PredictResponse"
                                        }
                                    }
                                },
                            },
                            "422": {"description": "Validation error"},
                            "500": {"description": "Internal error"},
                        },
                    }
                },
                "/health": {
                    "get": {
                        "summary": "Health check",
                        "operationId": "health",
                        "tags": ["ops"],
                        "responses": {
                            "200": {"description": "Service healthy"}
                        },
                    }
                },
                "/ready": {
                    "get": {
                        "summary": "Readiness probe",
                        "operationId": "ready",
                        "tags": ["ops"],
                        "responses": {
                            "200": {"description": "Service ready"},
                            "503": {"description": "Not ready"},
                        },
                    }
                },
                "/metrics": {
                    "get": {
                        "summary": "Prometheus metrics",
                        "operationId": "metrics",
                        "tags": ["ops"],
                        "responses": {
                            "200": {
                                "description": "Prometheus text format",
                                "content": {"text/plain": {"schema": {"type": "string"}}},
                            }
                        },
                    }
                },
            },
            "components": {
                "schemas": {
                    "PredictRequest": self._body_schema(self.meta.inputs),
                    "PredictResponse": self._body_schema(self.meta.outputs),
                }
            },
        }


# ---------------------------------------------------------------------------
# DockerfileGenerator
# ---------------------------------------------------------------------------

class DockerfileGenerator:
    """Generate an optimized multi-stage Dockerfile for the NIM service."""

    def __init__(self, metadata: ModelMetadata):
        self.meta = metadata

    def generate(self, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        df_path = output_dir / "Dockerfile"
        df_path.write_text(self._render(), encoding="utf-8")
        return df_path

    def _render(self) -> str:
        name = self.meta.name
        return textwrap.dedent(f"""\
            # syntax=docker/dockerfile:1.4
            # ─── Stage 1: build/install dependencies ────────────────────────────────────
            FROM python:3.12-slim AS builder

            WORKDIR /build

            # Install build tools
            RUN apt-get update && apt-get install -y --no-install-recommends \\
                    gcc \\
                && rm -rf /var/lib/apt/lists/*

            COPY requirements.txt .
            RUN pip install --no-cache-dir --prefix=/install -r requirements.txt


            # ─── Stage 2: runtime image ──────────────────────────────────────────────────
            FROM python:3.12-slim AS runtime

            LABEL org.opencontainers.image.title="{name}" \\
                  org.opencontainers.image.description="NVIDIA NIM-style inference service" \\
                  org.opencontainers.image.licenses="MIT"

            WORKDIR /app

            # Copy installed packages from builder
            COPY --from=builder /install /usr/local

            # Copy application and model
            COPY app.py .
            COPY model.onnx ./model.onnx

            # Non-root user for security
            RUN useradd -r -u 1000 nimuser && chown -R nimuser:nimuser /app
            USER nimuser

            EXPOSE 8000

            HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
                CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

            CMD ["python", "-m", "uvicorn", "app:app", \\
                 "--host", "0.0.0.0", "--port", "8000", \\
                 "--workers", "1", "--no-access-log"]
        """)
