# Generated deployment configuration\n{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "nimify-anything",
    "labels": {
      "app": "nimify-anything"
    }
  },
  "spec": {
    "replicas": 3,
    "selector": {
      "matchLabels": {
        "app": "nimify-anything"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "nimify-anything"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "nimify-anything",
            "image": "nimify-anything:latest",
            "ports": [
              {
                "containerPort": 8000,
                "name": "http"
              },
              {
                "containerPort": 9090,
                "name": "metrics"
              }
            ],
            "resources": {
              "requests": {
                "cpu": "500m",
                "memory": "1Gi",
                "nvidia.com/gpu": "1"
              },
              "limits": {
                "cpu": "2000m",
                "memory": "4Gi",
                "nvidia.com/gpu": "1"
              }
            },
            "env": [
              {
                "name": "ENV",
                "value": "production"
              },
              {
                "name": "LOG_LEVEL",
                "value": "INFO"
              },
              {
                "name": "METRICS_ENABLED",
                "value": "true"
              }
            ],
            "livenessProbe": {
              "httpGet": {
                "path": "/health",
                "port": 8000
              },
              "initialDelaySeconds": 30,
              "periodSeconds": 10
            },
            "readinessProbe": {
              "httpGet": {
                "path": "/ready",
                "port": 8000
              },
              "initialDelaySeconds": 5,
              "periodSeconds": 5
            }
          }
        ],
        "affinity": {
          "podAntiAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
              {
                "weight": 100,
                "podAffinityTerm": {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "app",
                        "operator": "In",
                        "values": [
                          "nimify-anything"
                        ]
                      }
                    ]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }
              }
            ]
          }
        }
      }
    }
  }
}